export const ACTION_SET_IS_FETCHING = "ACTION_SET_IS_FETCHING";
export const ACTION_LOAD_GRAPH = "ACTION_LOAD_GRAPH";
export const ACTION_SET_REQUEST_ERROR = "ACTION_SET_REQUEST_ERROR";
export const ACTION_CREATE_GRAPH = "ACTION_CREATE_GRAPH";
export const ACTION_SET_LOADED_GRAPHS = "ACTION_SET_LOADED_GRAPHS";
